apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: portal-sp-selfsigned-issuer-production
  namespace: laa-apply-for-criminal-legal-aid-production
spec:
  selfSigned: {}

---
# [LAA Portal PRODUCTION] -- https://portal.legalservices.gov.uk/oamfed/idp/metadata
#
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portal-sp-certificate-production
  namespace: laa-apply-for-criminal-legal-aid-production
spec:
  secretName: portal-sp-certificate-production
  issuerRef:
    name: portal-sp-selfsigned-issuer-production
    kind: Issuer
  isCA: false
  commonName: CrimeApply
  subject:
    organizations:
      - LAA
  duration: 87600h  # 10 years
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - content commitment
    - digital signature
    - data encipherment
    - key agreement
