apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-production
  namespace: laa-apply-for-criminal-legal-aid-production
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: ingress-production-laa-apply-for-criminal-legal-aid-production-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($host = 'laa-apply-for-criminal-legal-aid-production.apps.live.cloud-platform.service.justice.gov.uk') {
        return 301 https://laa-apply-for-criminal-legal-aid-production.apps.cloud-platform.service.justice.gov.uk;
      }
      if ($host = 'laa-apply-for-criminal-legal-aid-production.apps.cloud-platform.service.justice.gov.uk') {
        return 301 https://apply-for-criminal-legal-aid.service.justice.gov.uk;
      }
      location = /.well-known/security.txt {
        auth_basic off;
        return 301 https://raw.githubusercontent.com/ministryofjustice/security-guidance/main/contact/vulnerability-disclosure-security.txt;
      }
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecRequestBodyLimit 1048576
      SecRequestBodyNoFilesLimit 1048576
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-crime-apply"
      SecRuleUpdateTargetByTag attack-xss !REQUEST_COOKIES:_laa_apply_for_criminal_legal_aid_session
spec:
  ingressClassName: modsec
  tls:
  - hosts:
    - laa-apply-for-criminal-legal-aid-production.apps.live.cloud-platform.service.justice.gov.uk
    - laa-apply-for-criminal-legal-aid-production.apps.cloud-platform.service.justice.gov.uk
  - hosts:
    - apply-for-criminal-legal-aid.service.justice.gov.uk
    secretName: domain-tls-certificate-production
  rules:
  - host: laa-apply-for-criminal-legal-aid-production.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: service-production
            port:
              number: 80
  - host: laa-apply-for-criminal-legal-aid-production.apps.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: service-production
            port:
              number: 80
  - host: apply-for-criminal-legal-aid.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: service-production
            port:
              number: 80
