apiVersion: v1
kind: Service
metadata:
  name: service-production
  namespace: laa-apply-for-criminal-legal-aid-production
  labels:
    app: apply-for-criminal-legal-aid-web-production
spec:
  ports:
  - port: 80
    name: http
    targetPort: 3000
  selector:
    app: apply-for-criminal-legal-aid-web-production
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-production
  namespace: laa-apply-for-criminal-legal-aid-production
  labels:
    app: apply-for-criminal-legal-aid-web-production
spec:
  ports:
  - port: 9394
    name: metrics
    targetPort: 9394
  selector:
    app: apply-for-criminal-legal-aid-web-production
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-errors
  namespace: laa-apply-for-criminal-legal-aid-production
  labels:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: nginx-errors
    app.kubernetes.io/part-of: ingress-nginx
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
