---
# https://github.com/Shopify/erb-lint#configuration
#
EnableDefaultLinters: true
exclude:
  - 'node_modules/**/*'
  - 'lib/generators/**/*'
  - 'vendor/**/*'

linters:
  SpaceAroundErbTag:
    enabled: false
  PartialInstanceVariable:
    enabled: true
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      # There are some cops not suitable for ERB files,
      # disable or tweak as needed below
      Layout/InitialIndentation:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Style/BlockDelimiters:
        Enabled: false
      Style/MultilineIfModifier:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
