repos:
  - repo: https://github.com/ministryofjustice/devsecops-hooks
    rev: 53d252e406bae2bbbd0c0f3205b72870a02c9b3f  # v2.0.2
    hooks:
      - id: baseline
  - repo: local
    hooks:
      - id: rubocop
        name: rubocop
        entry: bundle exec rubocop --force-exclusion
        language: system
