plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

require:
  # Add custom cops for this project below
  - ./lib/rubocop/custom_cops/govuk_formbuilder/text_field_autocomplete.rb

AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "lib/tasks/**/*"
    - "lib/generators/**/*"
    - "features/**/*"
    - "vendor/**/*"

####################################
## Customization for this project ##
####################################

# Disabled cops
###############

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/EnumSyntax:
  Enabled: false

Naming/PredicateName:
  Enabled: false

# Rspec cops
############

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: true
  Exclude:
    - "**/spec/services/evidence/rules/*"

# Enabled but tweaked cops
##########################

# To be tweaked until we find the right balance
Metrics/MethodLength:
  Max: 12

Metrics/BlockLength:
  Exclude:
    - "**/app/services/evidence/rules/*"

# To be tweaked until we find the right balance
Metrics/AbcSize:
  Max: 18

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/HashSyntax
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: consistent

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Naming/BlockForwarding
Naming/BlockForwarding:
  EnforcedStyle: explicit

# https://rubydoc.info/gems/rubocop/0.82.0/RuboCop/Cop/Naming/MethodParameterName
Naming/MethodParameterName:
  AllowedNames:
    - as

# Rubocop mistakenly consider `#values` method as being called on a Hash
Style/HashEachMethods:
  Exclude:
    - app/value_objects/value_object.rb
    - app/forms/steps/case/ioj_form.rb

# Allow expectations with block syntax in tests, for improved readability
Style/BlockDelimiters:
  Exclude:
    - "spec/**/*"

# TODO: adjust these values towards the rubocop defaults
RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Max: 7
  Exclude:
    - spec/presenters/summary/sections/*

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 18
  Exclude:
    - spec/presenters/summary/sections/*
