# Simplify running the application inside a container locally.
# Usage: `docker-compose up`
#
# Do not use docker-compose in production environments.
#

volumes:
  clamav-signatures:

services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  clamav:
    image: ghcr.io/ministryofjustice/clamav-docker/laa-clamav:latest
    ports:
      - "3310:3310"
    volumes:
      - clamav-signatures:/var/lib/clamav
    environment:
      - FRESHCLAM_CHECKS=24
      - MIRROR_URL=https://laa-clamav-mirror-production.apps.live.cloud-platform.service.justice.gov.uk

  web:
    build: .
    environment:
      ENV_NAME: production
      RAILS_ENV: production
      DATABASE_URL: postgresql://postgres@db/laa-apply-for-criminal-legal-aid
      SECRET_KEY_BASE: f22760a0bd78a9191ba4c247e23a281cb251461cdba6b5215043ca11b694d734
      DATASTORE_API_ROOT: http://host.docker.internal:3003
      DATASTORE_API_AUTH_SECRET: foobar
      ENABLE_PROMETHEUS_EXPORTER: "false" # can be enabled for quick tests
      PROMETHEUS_EXPORTER_PORT: 9394
      RAILS_SERVE_STATIC_FILES: "1"
      RAILS_LOG_TO_STDOUT: "1"
      DATABASE_SSLMODE: disable
      DISABLE_HTTPS: "1"
      BC_USE_DEV_MOCK: "true"
      OMNIAUTH_TEST_MODE: "true"
      CLAMD_CONF_FILENAME: "clamd.docker.conf"
    ports:
      - "3000:3000" # puma server (rails app)
      - "9394:9394" # prometheus exporter `/metrics` endpoint
    depends_on:
      - db
