# List of providers (office codes and/or emails)
# who can use the service (phased private MVP access).
#
# If a provider has more than one office code, then
# access is granted if any code is allowed.
#
localhost:
  office_codes:
    - 1A123B # mock and tests
    - 1K022G # portal dev/stg test user

staging:
  office_codes:
    - 1A123B # mock and tests
    - 1K022G
    - 0Z981E

production:
  office_codes:
    - 1A123B # mock and tests
    - 2N232W # test provider in test firm
    # First onboarding tranche - 19/07/2023
    - 1T524L
    - 1Q101C
    - 1R281K
    - 1M383Y
    # Second onboarding tranche - 31/07/2023
    - 2A041V
    - 1W261L
    # Third onboarding tranche - 18/08/2023
    - 1Q921U
    # Fourth onboarding tranche - 22/08/2023
    - 0A701M
    - 0Q824N
    - 1P821Y
    - 1P864V
    - 2P443M
    - 1Y423L
    # Fifth onboarding tranche - 29/08/2023
    - 2P495U
    - 1P821Y
    # Sixth onboarding tranche - 05/09/2023
    - 0Q974B
    - 0R360W
    - 0R532H
    - 1P401R
    - 0R796V
    - 1N221J
    - 2Q544J
    - 0Z758M
    # Seventh onboarding tranche - 20/09/2023
    - 0M058V
    - 0V774G
    - 1K905R
    - 2L669X
    - 2L705L
    - 2M411D
    - 2M413F
    - 2N829V
    - 2N915N
    - 2P048H
    - 2P208G
    - 2P417J
    - 2P418K
    - 2P419L
    - 2Q226N
    - 2Q229R
    - 2Q525N
    - 2Q528R
    - 2Q530U
    - 2Q531V
    - 2Q534Y
    - 2Q535Z
    - 2Q536A
    # Eighth onboarding tranche - 04/10/2023
    - 0J180R
    - 0Q690T
    - 0R795U
    - 0U542T
    - 0U563Q
    # Ninth onboarding tranche - 09/10/2023
    - 0R225Z
    - 2C101J
    - 2F801F
    - 2M030P
    - 2N823N
    - 2N824P
    - 2N842J
    - 2P169P
    - 2P287T
    - 2P288U
    - 2Q419Y
    - 2Q422B
