# List of providers (office codes and/or emails)
# who can use the service (phased private MVP access).
#
# If a provider has more than one office code, then
# access is granted if any code is allowed.
#
localhost:
  office_codes:
    - 1A123B # mock and tests
    - 1K022G # portal dev/stg test user

staging:
  office_codes:
    - 1A123B # mock and tests
    - 1K022G
    - 0Z981E

production:
  office_codes:
    - 1A123B # mock and tests
    - 2N232W # test provider in test firm
