# List of providers office codes that are inactive.
#
# Temporary solution to allow us to onboard over the next few months.
# Plan is to build an API to glean this info from other systems, but
# in the intrim this this was agreed as a way to continue onboarding.
#
# This is used by Provider::ActiveOfficeChecker to filter out inactive
# offices from the array that Crime Apply receives from the portal auth_info
#
# This happens after the Provider::Gatekeeper has filtered out providers
# that have not been onboarded yet in Providers::OmniauthCallbacksController.
#
#
localhost:
  inactive_office_codes:
    - 3B345C
    - 4C567D

staging:
  inactive_office_codes:
    # Uncomment to test feature on staging
    # - 0A719G

production:
  inactive_office_codes:
    # Inactive codes up to sixth onboarding tranche - 07/09/23
    - 0R918C
    - 2M353Q
    # Inactive codes for seventh onboarding tranche - 20/09/23
    - 2M410C
    - 2M412E
    - 2N826R
    - 2N827T
    - 2N828U
    - 2P049J
    - 2P050K
    - 2P420M
    - 2Q526P
    - 2Q527Q
    - 2Q529T
    - 2Q532W
    - 2Q533X
    - 2Q537B
    - 2Q538C
    - 2Q539D
    - 2Q573Q
    # Inactive codes for eighth onboarding tranche - 04/10/2023
    - 0J683N
    - 0Q806U
    - 2M861T
    - 0R178Y
    # Inactive codes for ninth onboarding tranche - 09/10/2023
    - 2Q420Z
    - 2Q421A
    - 166YR
    - 5872H
    # Inactive codes for tenth onboarding tranche - 19/10/2023
    - 2E301A
    - 0J981M
    - 1F021H
    - 2M415H
    - 2P425T
    # Inactive codes for eleventh onboarding tranche - 24/10/2023
    - 0F080X
    - 0F919J
    - 0J975F
    - 0W660V
    - 2M050L
    - 2M263T
    - 2L547P
    - 2L548Q
    - 2M072K
    - 2P492Q
    - 2N418Y
    - 2L812C
    - 0H663E
    - 1L461W
    - 2N327Z
    - 2N330C
    - 2P181C
    - 2P477Z
    - 2P478A
    - 2P480C
    - 2Q201L
    - 2Q267H
    - 2Q415U
    - 0J177N
    - 0L787A
    - 2P397M
    - 2N952D
    - 2M127V
    # Inactive codes for twelfth onboarding tranche - 06/11/2023
    - 2N854X
    - 2Q213Z
    - 2P571B
    - 0P181C
    - 0X135L
    - 2P879L
    - 0R404U
    - 1Z821F
    - 2L587H
    - 2L588J
    - 1C541M
    - 1Q123B
    - 2N848Q
    - 2M269Z
    - 2P307P
    - 0R135B
    - 0R654Q
    - 2M290X
    - 2P449U
    - 0H348M
    - 0L863H
    # Inactive codes for thirteenth onboarding tranche - 20/11/2023
    - 1N641Q
    - 0N065P
    - 2M545Z
    - 2Q133M
    - 2M986D
    - 2N273Q
    - 0V679D
    - 0V752H
    - 2P624J
    - 2P625K
    - 2P626L
    - 2P627M
    - 2L720C
    - 0P196U
    - 2M938B
    - 0N288G
    - 2Q015J
    - 0R402R
    - 0N585E
    - 1R761G
    - 2E921Z
    - 1P681W
    - 1Y081P
    - 0N787Z
    - 2D041F
    - 2A561K
    - 2E841M
    - 2L866L
    # Deactivate codes 20/11/2023
    - 0N019P
    - 0N581A
    - 2L982M
    - 2M286T
    - 2Q102D
    - 2Q103E
    # Deactivate codes 30/11/2023
    - 0L290K
    - 0V021N
    # Inactive codes for fourteenth onboarding tranche - 30/11/2023
    - 0Y265P
    - 0C179U
    - 2P851F
    - 2Q189Y
    - 2Q190Z
    - 0N156N
    - 0L225P
    - 2N269L
    - 2P630Q
    - 0F124V
    - 0F376U
    - 0F593E
    - 2M939C
    - 2P046F
    - 2Q216C
    - 0M345G
    - 0Q698B
    - 1M561R
    - 2A862M
    - 2M190N
    - 0C002B
    - 1B762Q
    - 0P480C
    - 0R142J
    - 0R332Q
    - 0U556H
    - 0U599E
    - 2N964R
    - 2N965T
    - 2N966U
    - 0Z559W
    - 0C063T
    - 0R275D
    - 0V481N
    - 2L693Y
    - 2L695A
    - 2M349L
    - 2M880N
    - 2M881P
    - 2N163W
    - 0H428Z
    - 0E160X
    - 0E813G
    - 2Q040L
    - 2Q626Y
    - 2N206T
    - 2P629P
    - 0P489M
    - 0H232L
    - 0R658V
    - 0J516G
    - 0W123L
    - 2M584R
    - 2N138U
    - 0X174D
    - 2E981P
    - 2M288V
    - 2P652P
    - 0C063T
    - 0Q801N
    - 0W336T
    - 0W551B
    - 2L583D
    - 2L737W
    - 2L766C
    - 2N030B
    - 0C992C
    - 0D024M
    - 0K035W
    - 2N418Y
    - 0B284W
    - 0T240C
    - 0U422M
    - 2P581M
    - 2P582N
    - 0T047T
    - 0T057D
    - 0T377B
    - 0U162E
    - 0R239P
    - 2Q615L
    - 2Q658H
    - 0H287W
    - 2M332T
    - 1R601H
    - 2M241U
    - 2M247A
    - 2P619D
    - 2Q248M
    - 2Q475J
    - 2Q476K
    - 2Q477L
    - 0P003J
    - 0P496V
    - 1D102X
    - 0D203G
    - 0D361D
    - 0D825H
    - 0N086M
    - 0N567K
    - 2N288G
    - 1P502B
    - 1Q862E
    - 0W044A
    - 2M930T
    - 0E078H
    - 2L913M
    - 2L922X
    - 2P251D
    - 2M923K
    - 2P276F
    # Make onboarded codes inactive - 08/12/2023
    - 0D619J
    - 2P662A
    - 2E961T
    - 2M743P
    - 2Q748F
    - 0Z530P
    - 0R446P
    - 2L946Y
    - 0E368Y
    - 0Q018M
    - 1B182K
    - 2P628N
    - 2P991H
    - 0N057F
    - 0F124V
    - 0F593E
    - 2M939C
    - 0G987V
    - 2N272P
    - 0X785T
    - 0X003T
    - 0T174F
    - 0T862D
    - 2F121R
    - 1B763R
    - 0R978T
    - 2L966V
    - 2N812B
    - 2N648Y
    - 0C411W
    - 0R064Z
    - 0H428Z
    - 0E160X
    - 0E813G
    - 0N783V
    - 0N992X
    - 2Q040L
    - 0P618C
    - 0Z208P
    - 2C761B
    - 2M945J
    - 2P975Q
    - 2P976R
    - 0J067U
    - 2P696M
    - 0C735Y
    - 2Q116U
    - 0N467B
    - 2N654E
    - 0H573G
    - 0B048P
    - 0H279M
    - 0P053N
    - 0P965E
    - 0Q066P
    - 0P974P
    - 0C411W
    - 0J496K
    - 0A022Z
    - 0C876B
    - 0D024M
    - 0D058Z
    - 0H089F
    - 2P841V
    - 2Q079D
    - 2Q729K
    - 0T009B
    - 0U222V
    - 2P663B
    - 0T131J
    - 2N794G
    - 2N795H
    - 0T530T
    - 0L304A
    - 0L304A
    - 0P003J
    - 0P496V
    - 2Q674A
    - 2Q675B
    - 0T429H
    - 0T431K
    - 2N636K
    - 2Q691U
    - 2Q696Z
    - 0N324W
    - 0N047V
    - 0V161Q
    - 2L990W
    - 0T853U
    - 0W174R
    - 1P769R
    - 0N814D
    - 0P319C
    - 0P221W
    - 0R045D
