# List of providers office codes that are inactive.
#
# Temporary solution to allow us to onboard over the next few months.
# Plan is to build an API to glean this info from other systems, but
# in the intrim this this was agreed as a way to continue onboarding.
#
# This is used by Provider::ActiveOfficeChecker to filter out inactive
# offices from the array that Crime Apply receives from the portal auth_info
#
# This happens after the Provider::Gatekeeper has filtered out providers
# that have not been onboarded yet in Providers::OmniauthCallbacksController.
#
#
localhost:
  inactive_office_codes:
    - 3B345C
    - 4C567D

staging:
  inactive_office_codes:
    # Uncomment to test feature on staging
    # - 0A719G

production:
  inactive_office_codes:
    # Inactive codes up to sixth onboarding tranche - 07/09/23
    - 0R918C
    - 2M353Q
    # Inactive codes for seventh onboarding tranche - 20/09/23
    - 2M410C
    - 2M412E
    - 2N826R
    - 2N827T
    - 2N828U
    - 2P049J
    - 2P050K
    - 2P420M
    - 2Q526P
    - 2Q527Q
    - 2Q529T
    - 2Q532W
    - 2Q533X
    - 2Q537B
    - 2Q538C
    - 2Q539D
    - 2Q573Q
    # Inactive codes for eighth onboarding tranche - 04/10/2023
    - 0J683N
    - 0Q806U
    - 2M861T
    - 0R178Y
    # Inactive codes for ninth onboarding tranche - 09/10/2023
    - 2Q420Z
    - 2Q421A
    - 166YR
    - 5872H
