apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: portal-sp-selfsigned-issuer-staging
  namespace: laa-apply-for-criminal-legal-aid-staging
spec:
  selfSigned: {}

---
# [LAA Portal DEV] -- https://portal.dev.legalservices.gov.uk/oamfed/idp/metadata
# NOTE: We don't have a corresponding Apply DEV, but we can use this cert for
# localhost tests
#
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portal-sp-certificate-dev
  namespace: laa-apply-for-criminal-legal-aid-staging
spec:
  secretName: portal-sp-certificate-dev
  issuerRef:
    name: portal-sp-selfsigned-issuer-staging
    kind: Issuer
  isCA: false
  commonName: CrimeApply
  subject:
    organizations:
      - LAA
  duration: 87600h # 10 years
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - content commitment
    - digital signature
    - data encipherment
    - key agreement

---
# [LAA Portal STAGING] -- https://portal.uat.legalservices.gov.uk/oamfed/idp/metadata
#
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portal-sp-certificate-staging
  namespace: laa-apply-for-criminal-legal-aid-staging
spec:
  secretName: portal-sp-certificate-staging
  issuerRef:
    name: portal-sp-selfsigned-issuer-staging
    kind: Issuer
  isCA: false
  commonName: CrimeApply
  subject:
    organizations:
      - LAA
  duration: 87601h # 10 years
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - content commitment
    - digital signature
    - data encipherment
    - key agreement
