apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-staging
  namespace: laa-apply-for-criminal-legal-aid-staging
data:
  ENV_NAME: staging
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: enabled
  RAILS_LOG_TO_STDOUT: enabled
  GA_TRACKING_ID: G-5V1GTJM5K7
  SESSION_TIMEOUT_MINUTES: "60"
  REAUTHENTICATE_AFTER_MINUTES: "720"
  ENABLE_PROMETHEUS_EXPORTER: "true"
  CLAMD_CONF_FILENAME: "clamd.staging.conf"
  DATASTORE_API_ROOT: http://service-staging.laa-criminal-applications-datastore-staging.svc.cluster.local
  BC_WSDL_URL: https://uat.laa-benefit-checker.service.justice.gov.uk/lsx/lsc-services/benefitChecker?wsdl
  VIRUS_SCAN_TIMEOUT: "20"
  OMNIAUTH_ENTRA_CLIENT_ID: abd5ebbe-44b2-4c14-b815-a741ebfd21b2
  OMNIAUTH_ENTRA_TENANT_ID: ff260a8b-cb92-4cfe-8ae9-d48bb0fd9851
  OMNIAUTH_ENTRA_REDIRECT_URI: https://staging.apply-for-criminal-legal-aid.service.justice.gov.uk/providers/auth/entra/callback
  OMNIAUTH_ENTRA_POST_LOGOUT_REDIRECT_URI: https://staging.apply-for-criminal-legal-aid.service.justice.gov.uk/providers/logout
  PROVIDER_DATA_API_URL: https://laa-provider-details-api-prod.apps.live.cloud-platform.service.justice.gov.uk
  RETENTION_PERIOD: "2" # 2 years
  SOFT_DELETION_PERIOD: "2" # 2 weeks


  # If this is uncommented, authentication will be mocked
  # OMNIAUTH_TEST_MODE: "true"
