apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-staging
  namespace: laa-apply-for-criminal-legal-aid-staging
data:
  ENV_NAME: staging
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: enabled
  RAILS_LOG_TO_STDOUT: enabled
  GA_TRACKING_ID: G-5V1GTJM5K7
  SESSION_TIMEOUT_MINUTES: "60"
  REAUTHENTICATE_AFTER_MINUTES: "1440"
  ENABLE_PROMETHEUS_EXPORTER: "true"
  CLAMD_CONF_FILENAME: "clamd.staging.conf"
  DATASTORE_API_ROOT: http://service-staging.laa-criminal-applications-datastore-staging.svc.cluster.local
  BC_WSDL_URL: https://benefitchecker.stg.legalservices.gov.uk/lsx/lsc-services/benefitChecker?wsdl
  VIRUS_SCAN_TIMEOUT: '20'

  # If this is uncommented, authentication will be mocked
  # OMNIAUTH_TEST_MODE: "true"

  # LAA Portal metadata endpoint or file
  # (endpoint not accessible from inside CP, using locally stored file)
  #
  # Important: make sure whatever Portal env is declared here, uses the
  # corresponding certificates, if required (in `deployment.tpl` file)
  #
  LAA_PORTAL_IDP_METADATA_FILE: config/laa_portal/metadata/staging.xml
