apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-staging
  namespace: laa-apply-for-criminal-legal-aid-staging
data:
  ENV_NAME: staging
  RACK_ENV: production
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: enabled
  # Datastore endpoint for staging
  DATASTORE_API_ROOT: https://criminal-applications-datastore-staging.apps.live.cloud-platform.service.justice.gov.uk
  # LAA Portal metadata endpoint
  # (not accessible from inside CP it seems, using test mode for now)
  LAA_PORTAL_IDP_METADATA_URL: https://samlmock.dev.legalservices.gov.uk/metadata
  OMNIAUTH_TEST_MODE: true
