apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clamav-staging
  namespace: laa-apply-for-criminal-legal-aid-staging
spec:
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 15
  serviceName: clamav
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: apply-for-criminal-legal-aid-clamav-staging
  template:
    metadata:
      labels:
        app: apply-for-criminal-legal-aid-clamav-staging
        tier: backend
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: clamav
          image: ghcr.io/ministryofjustice/clamav-docker/laa-clamav:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3310
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/clamav
              name: clamav-signatures
          env:
            - name: FRESHCLAM_CHECKS
              value: "24"
            - name: MIRROR_URL
              value: https://laa-clamav-mirror-production.apps.live.cloud-platform.service.justice.gov.uk
          resources:
            requests:
              cpu: 25m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 3Gi
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - echo "started" > /tmp/starttest && clamdscan --no-summary /tmp/starttest
            failureThreshold: 60
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3310
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - clamdscan --no-summary /tmp/starttest
            periodSeconds: 30
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: clamav-signatures
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: clamav-service-staging
  namespace: laa-apply-for-criminal-legal-aid-staging
  labels:
    app: apply-for-criminal-legal-aid-clamav-staging
spec:
  ports:
    - port: 3310
      name: clamav
      targetPort: 3310
  selector:
    app: apply-for-criminal-legal-aid-clamav-staging
