{
 "title": "LAA Crime Apply / Golden Signals",
 "description": "High level application HTTP request and resource usage information.",
 "tags": [
  "CrimeApply",
  "nginx-ingress"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "description": "The number of HTTP requests per second received via the ingress.",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Rate Per Second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests Served",
   "type": "stat",
   "description": "The total number of requests served in the selected time period.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}[10m]))"
    }
   ]
  },
  {
   "title": "Mean Response Time (p100)",
   "type": "stat",
   "description": "The mean response time (p100 - all requests) over the selected timeframe.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1,max(irate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"$namespace\"}[1m])) by (le)) > 0"
    }
   ]
  },
  {
   "title": "Mean Response Time (p95)",
   "type": "stat",
   "description": "The mean response time (p95 - the 95th percentile of requests) over the selected timeframe.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,max(irate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"$namespace\"}[1m])) by (le)) > 0"
    }
   ]
  },
  {
   "title": "Mean Response Time (p50)",
   "type": "stat",
   "description": "The mean response time (p50 - the 50th percentile requests) over the selected timeframe.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,max(irate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"$namespace\"}[1m])) by (le)) > 0"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "description": "The percentage of HTTP responses that are non-error codes vs error codes.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", status!~\"5.*|499\"}[1m])) / sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}[1m])) * 100",
     "legendFormat": "Request Success Rate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "Recorded request duration from the ingress controllers in percentiles.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,max(irate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95,max(irate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(1,max(irate(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace=\"$namespace\"}[1m])) by (le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "The percentage of all HTTP requests that result in a 5xx status.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", status=\"500\"}[1m])) / sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}[5m])) * 100",
     "legendFormat": "500"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", status=\"501\"}[1m])) / sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}[5m])) * 100",
     "legendFormat": "501"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", status=\"502\"}[1m])) / sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}[5m])) * 100",
     "legendFormat": "502"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", status=\"503\"}[1m])) / sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}[5m])) * 100",
     "legendFormat": "503"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", status=\"504\"}[1m])) / sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}[5m])) * 100",
     "legendFormat": "504"
    }
   ]
  },
  {
   "title": "Blocked Requests",
   "type": "graph",
   "description": "This chart shows the number of blocked requests at the ingress level.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", status=\"429\"}[1m])) or vector(0)",
     "legendFormat": "Rate Limited Reqs"
    },
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", status=\"406\"}[1m])) or vector(0)",
     "legendFormat": "Mod Security Blocked Reqs"
    }
   ]
  },
  {
   "title": "Requested CPU Usage",
   "type": "graph",
   "description": "CPU usage in relation to the requested cpu for the container.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\", container=~\".+\"}[1m])) by (container) / avg(kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Actual CPU Usage",
   "type": "graph",
   "description": "Average recorded CPU usage for each type container within the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"POD\", container=~\".+\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "The amount of data being sent to and from the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"$namespace\"}[2m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[2m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Requested Memory Usage",
   "type": "graph",
   "description": "Memory usage in relation to the requested memory for the container.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "percent", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_memory_usage_bytes{namespace=\"$namespace\", container!=\"POD\", container=~\".+\"}[1m])) by (container) / avg(kube_pod_container_resource_requests{resource=\"memory\", namespace=\"$namespace\"}) by (container) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Actual Memory Usage",
   "type": "graph",
   "description": "Average recorded memory usage for a single type of container within the pods.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_memory_usage_bytes{namespace=\"$namespace\", container!=\"POD\", container=~\".+\"}[1m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Pod Replicas",
   "type": "graph",
   "description": "The number of pod replicas for the service.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "count(label_replace(kube_pod_info{namespace=\"$namespace\"}, \"pod\", \"$1\", \"created_by_name\", \"(.*)-\\\\w+\")) by (pod)",
     "legendFormat": "{{ created_by_name }}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "description": "This chart shows the count of pod/container restart events observed.  This will show \"CrashLooping\" error events.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[10m])) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Non-Ready Pods",
   "type": "timeseries",
   "description": "This chart shows the count of pods in an \"non-ready\" state.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_status_phase{namespace=\"$namespace\", phase=~\"Pending|Unknown\"}) > 0",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}