{
 "title": "LAA Crime Apply / Applications Dashboard",
 "tags": [
  "CrimeApply",
  "custom"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Crime Apply Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "STARTED",
   "type": "stat",
   "description": "An application is started the moment a provider clicks the button 'Make a new application'",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, ruby_crime_apply_applications_count{status=\"started\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "IN PROGRESS",
   "type": "stat",
   "description": "An application is considered in progress when at least the applicant’s first name has been entered",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, ruby_crime_apply_applications_count{status=\"in_progress\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "DATE STAMPED",
   "type": "stat",
   "description": "The application has been date stamped (not all case types produce date stamp)",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, ruby_crime_apply_applications_count{status=\"date_stamped\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "STALE (> 1 WEEK)",
   "type": "stat",
   "description": "An application is considered stale if it has not been updated for more than 1 week.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, ruby_crime_apply_applications_count{status=\"stale\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Applications by status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(avg(ruby_crime_apply_applications_count{namespace=\"$namespace\"}) by (status))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Crime Apply Providers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "ENROLLED",
   "type": "stat",
   "description": "Providers that have access to the service and have signed in at least once",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, ruby_crime_apply_providers_count{status=\"enrolled\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "MULTI OFFICE",
   "type": "stat",
   "description": "Providers with more than one office",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, ruby_crime_apply_providers_count{status=\"multi_office\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "DISENGAGED",
   "type": "stat",
   "description": "Providers that have not signed any declaration yet (no submissions), even if they have used the service",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, ruby_crime_apply_providers_count{status=\"disengaged\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "IDLE (> 1 WEEK)",
   "type": "stat",
   "description": "Providers that have not signed in to the service for a long period of time",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, ruby_crime_apply_providers_count{status=\"idle\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Providers by status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(avg(ruby_crime_apply_providers_count{namespace=\"$namespace\"}) by (status))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Crime Apply Provider Offices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "OFFICES",
   "type": "stat",
   "description": "Total number of unique enrolled provider offices",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, ruby_crime_apply_provider_offices_count{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Number of offices",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(avg(ruby_crime_apply_provider_offices_count{namespace=\"$namespace\"}))",
     "legendFormat": "Offices"
    }
   ]
  }
 ]
}