# internal healthcheck ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-staging-internal
  namespace: laa-apply-for-criminal-legal-aid-staging
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: ingress-staging-internal-laa-apply-for-criminal-legal-aid-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* ^/(health|readyz|startupz|datastore/health) {
        deny all;
      }
---
# pingdom ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-staging-pingdom
  namespace: laa-apply-for-criminal-legal-aid-staging
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: ingress-staging-pingdom-laa-apply-for-criminal-legal-aid-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-crime-apply"
      SecRule REMOTE_ADDR "!@ipMatch 212.78.83.12,212.78.83.16,23.106.37.99" \
        "id:5001,deny,status:403,tag:github_team=laa-crime-apply"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_method !~ ^GET$) {
        return 405;
      }
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($scheme = http) {
        return 444;
      }
spec:
  ingressClassName: modsec
  rules:
    - host: staging.apply-for-criminal-legal-aid.service.justice.gov.uk
      http:
        paths:
          - path: /ping
            pathType: Exact
            backend:
              service:
                name: service-staging
                port:
                  number: 80
          - path: /datastore/ping
            pathType: Exact
            backend:
              service:
                name: service-staging
                port:
                  number: 80
---
# public ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-staging-public
  namespace: laa-apply-for-criminal-legal-aid-staging
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: ingress-staging-public-laa-apply-for-criminal-legal-aid-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($scheme = http) {
        return 444;
      }
      location = /.well-known/security.txt {
        auth_basic off;
        return 301 https://raw.githubusercontent.com/ministryofjustice/security-guidance/main/contact/vulnerability-disclosure-security.txt;
      }
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-crime-apply"

spec:
  ingressClassName: modsec
  rules:
    - host: staging.apply-for-criminal-legal-aid.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: service-staging
                port:
                  number: 80
          - path: /cookies
            pathType: Exact
            backend:
              service:
                name: service-staging
                port:
                  number: 80
          - path: /about
            pathType: Prefix
            backend:
              service:
                name: service-staging
                port:
                  number: 80
          - path: /errors
            pathType: Prefix
            backend:
              service:
                name: service-staging
                port:
                  number: 80

---
# application ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-staging
  namespace: laa-apply-for-criminal-legal-aid-staging
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: ingress-staging-laa-apply-for-criminal-legal-aid-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/custom-http-errors: "423"
    nginx.ingress.kubernetes.io/default-backend: "nginx-errors"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine On
      SecRequestBodyLimit 15728640
      SecRequestBodyNoFilesLimit 1048576
      SecRule &REQUEST_COOKIES:_laa_apply_for_criminal_legal_aid_session "@eq 0" \
        "id:999,phase:1,deny,status:403,tag:github_team=laa-crime-apply"
      SecDefaultAction "phase:2,pass,log,tag:github_team=laa-crime-apply,status:423"
      SecRuleUpdateTargetById 942100 !ARGS:authenticity_token
      SecRule REQUEST_URI "@endsWith /documents" \
        "id:1000,phase:2,pass,nolog,\
        ctl:ruleRemoveById=921110,\
        ctl:ruleRemoveById=920120"
      SecRule REQUEST_URI "@endsWith /steps/case/ioj" \
        "id:1001,phase:2,pass,nolog,\
        ctl:ruleRemoveById=921110,\
        ctl:ruleRemoveById=932100,\
        ctl:ruleRemoveById=932110,\
        ctl:ruleRemoveById=932115,\
        ctl:ruleRemoveById=932125,\
        ctl:ruleRemoveById=932235,\
        ctl:ruleRemoveById=932370,\
        ctl:ruleRemoveById=932380,\
        ctl:ruleRemoveById=933210,\
        ctl:ruleRemoveById=942100,\
        ctl:ruleRemoveById=942230"
      SecRule REQUEST_URI "@endsWith /steps/submission/more-information" \
        "id:1002,phase:2,pass,nolog,\
        ctl:ruleRemoveById=921110,\
        ctl:ruleRemoveById=932100,\
        ctl:ruleRemoveById=932110,\
        ctl:ruleRemoveById=932115,\
        ctl:ruleRemoveById=932125,\
        ctl:ruleRemoveById=932235,\
        ctl:ruleRemoveById=932370,\
        ctl:ruleRemoveById=932380,\
        ctl:ruleRemoveById=933210,\
        ctl:ruleRemoveById=942100,\
        ctl:ruleRemoveById=942230"
      SecRule REQUEST_URI "@endsWith /steps/circumstances/pre-cifc-reason" \
        "id:1003,phase:2,pass,nolog,\
        ctl:ruleRemoveById=921110,\
        ctl:ruleRemoveById=932100,\
        ctl:ruleRemoveById=932110,\
        ctl:ruleRemoveById=932115,\
        ctl:ruleRemoveById=932125,\
        ctl:ruleRemoveById=932235,\
        ctl:ruleRemoveById=932370,\
        ctl:ruleRemoveById=932380,\
        ctl:ruleRemoveById=933210,\
        ctl:ruleRemoveById=942100,\
        ctl:ruleRemoveById=942230"
      SecRule REQUEST_URI "@endsWith /steps/case/client/other-charge" \
        "id:1004,phase:2,pass,nolog,\
        ctl:ruleRemoveById=932110,\
        ctl:ruleRemoveById=932115,\
        ctl:ruleRemoveById=942230"
      SecRule REQUEST_URI "@endsWith /steps/case/partner/other-charge" \
        "id:1005,phase:2,pass,nolog,\
        ctl:ruleRemoveById=932110,\
        ctl:ruleRemoveById=932115,\
        ctl:ruleRemoveById=942230"
      SecRule REQUEST_URI "@rx .*/steps/capital/investments/[a-f0-9-]+$" \
        "id:1006,phase:2,pass,nolog,\
        ctl:ruleRemoveById=932110,\
        ctl:ruleRemoveById=932115"
      SecRule REQUEST_URI "@rx .*/steps/case/charges/[a-f0-9-]+$" \
        "id:1007,phase:2,pass,nolog,\
        ctl:ruleRemoveById=933210,\
        ctl:ruleRemoveById=942100"
      SecRule REQUEST_URI "@endsWith /steps/income/how-manage-with-no-income" \
        "id:1008,phase:2,pass,nolog,\
        ctl:ruleRemoveById=921110,\
        ctl:ruleRemoveById=932100,\
        ctl:ruleRemoveById=932110,\
        ctl:ruleRemoveById=932115,\
        ctl:ruleRemoveById=932125,\
        ctl:ruleRemoveById=932235,\
        ctl:ruleRemoveById=932370,\
        ctl:ruleRemoveById=932380,\
        ctl:ruleRemoveById=933210,\
        ctl:ruleRemoveById=942100,\
        ctl:ruleRemoveById=942230"
      SecRule REQUEST_URI "@streq /providers/auth/saml/callback" \
        "id:1010,phase:2,pass,nolog,chain"
        SecRule REQUEST_METHOD "@streq POST" \
          "ctl:ruleRemoveById=921110,\
          ctl:ruleRemoveById=932235,\
          ctl:ruleRemoveById=932250,\
          ctl:ruleRemoveById=932260,\
          ctl:ruleRemoveById=932370,\
          ctl:ruleRemoveById=933150,\
          ctl:ruleRemoveById=941130"
      SecRuleUpdateTargetByTag attack-rce !REQUEST_COOKIES:_laa_apply_for_criminal_legal_aid_session
      SecRuleUpdateTargetByTag attack-sqli !REQUEST_COOKIES:_laa_apply_for_criminal_legal_aid_session
      SecRuleUpdateTargetByTag attack-xss !REQUEST_COOKIES:_laa_apply_for_criminal_legal_aid_session
      SecRuleUpdateTargetByTag attack-injection-php !REQUEST_COOKIES:_laa_apply_for_criminal_legal_aid_session
spec:
  ingressClassName: modsec
  tls:
    - hosts:
        - laa-apply-for-criminal-legal-aid-staging.apps.live.cloud-platform.service.justice.gov.uk
        - laa-apply-for-criminal-legal-aid-staging.apps.cloud-platform.service.justice.gov.uk
    - hosts:
        - staging.apply-for-criminal-legal-aid.service.justice.gov.uk
      secretName: domain-tls-certificate-staging
  rules:
    - host: laa-apply-for-criminal-legal-aid-staging.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-staging
                port:
                  number: 80
    - host: laa-apply-for-criminal-legal-aid-staging.apps.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-staging
                port:
                  number: 80
    - host: staging.apply-for-criminal-legal-aid.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-staging
                port:
                  number: 80
